### ISSUE TITLE
Propose a clearer Abstract

### ISSUE THREAD

**Issue by andorsk** [trustoverip/tswg-trust-registry-protocol#34]
Not sure if the abstract is quite clear. It goes right into the forward. Can we make it more clear what the overview of the spec is at the beginning and clarify for new audiences what we are doing? It goes right into https://trustoverip.github.io/tswg-trust-registry-protocol/#on-trust-trustworthy-and-trustworthiness.

**Comment by a-fox** [comment]
[Create a new large(ish) PR](https://github.com/trustoverip/tswg-trust-registry-protocol/pull/39).
- Wrote new introduction chapter (scope)
- Restructured the content according to ToIP spec format.
- Consolidated repeating chapters to one (in scope + introduction)
- Moved inline terms to own terms chapter

**Comment by darrellodonnell** [comment]
good to close?
