### ISSUE TITLE
Make it easier to look for schemas in the spec

### ISSUE THREAD

**Issue by andorsk** [trustoverip/tswg-trust-registry-protocol#37]
https://app.swaggerhub.com/apis-docs/continuumloop/trust-over_ip_trust_registry_protocol_res_tful_api_v_2/2.0.0

**Comment by darrellodonnell** [comment]
would a "Implementer Note" with just a few bullets at the top (and duplicated in the readme.md?) help?

**Comment by davepoltorak** [comment]
@andorsk Can you please adjust the description of the issue to explain the problem you see and the solution you are proposing? It can then be discussed sync/async

**Comment by andorsk** [comment]
I'm closing this as I did not do a good job properly expressing the need here and honestly have forgotten what was required. Likely a note that was supposed to be further clarified but was not.
