### ISSUE TITLE
DID Profiles / Service Discovery

### ISSUE THREAD

**Issue by darrellodonnell** [trustoverip/tswg-trust-registry-protocol#5]
With the advent of the DID Profiles concept it may be better to use (and show) that concept.

The following was in the v1 spec and is helpful, but doesn't exercise the DID Profiles concept. 

<img width="533" alt="image" src="https://github.com/trustoverip/tswg-trust-registry-protocol/assets/686855/f5cd6ccd-1758-4b0c-813a-244103ee8212">

**Comment by darrellodonnell** [comment]
@andorsk I didn't want to assign this to you, but...

**Comment by darrellodonnell** [comment]
relates to work in SDTF - https://wiki.trustoverip.org/display/HOME/Service+Discovery+Task+Force

**Comment by andorsk** [comment]
This is helpful @darrellodonnell . Thank you

**Comment by andorsk** [comment]
In #7

**Comment by andorsk** [comment]
This was done. Closing.
