### ISSUE TITLE
YAML link results in 404

### ISSUE THREAD

**Issue by tkuhrt** [trustoverip/tswg-trust-registry-protocol#50]
The link in [Section 8](https://trustoverip.github.io/tswg-trust-registry-protocol/#annex-b-openapi-specification) for the [OAS (.yaml) for TRP v2](https://trustoverip.github.io/api/toip-tswg-trustregistryprotocol-v2.yaml) results in a 404 error.

**Comment by darrellodonnell** [comment]
thx.

I also not that the wrong file is linked on SwaggerHub .

**Comment by darrellodonnell** [comment]
correct link to (unversioned - main branch) file is: https://github.com/trustoverip/tswg-trust-registry-protocol/blob/main/api/toip-tswg-trustregistryprotocol-v2.yaml

**Comment by davepoltorak** [comment]
Clicking on the link in Section 8 as Tracy linked now works and points to the address Darrell posted. This looks like it's been fixed and can be closed.

**Comment by tkuhrt** [comment]
Agree. Closing issue.
